[target.xtensa-esp32s3-none-elf]
#runner = "espflash flash --monitor"
runner = "espflash flash -p /dev/cu.usbserial-12420"

[env]
ESP_LOGLEVEL="INFO"
[build]
rustflags = [
  "-C", "link-arg=-Tlinkall.x",
"-C", "link-arg=-Trom_functions.x",

  "-C", "link-arg=-nostartfiles",
]

target = "xtensa-esp32s3-none-elf"

[unstable]
build-std = ["core"]
